# Generated by Django 5.2.7 on 2025-11-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_userlibrary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FPS', 'First-Person Shooter'), ('RPG', 'Role-Playing Game'), ('MOBA', 'Multiplayer Online Battle Arena'), ('SIM', 'Simulation'), ('HORROR', 'Horror'), ('Indie', 'Indie')], default='INDIE', max_length=20),
        ),
    ]
