# Generated by Django 5.2.7 on 2025-11-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlibrary',
            options={'verbose_name_plural': 'User Libraries'},
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='products',
            field=models.ManyToManyField(blank=True, to='store.product'),
        ),
    ]
